package pipeline

import (
	"archive/zip"
	"bytes"
	"io"
	"math/rand"
	"os"
	"path/filepath"
	"testing"

	"github.com/AzozzALFiras/GoSigner/certificate/loader"
	"github.com/AzozzALFiras/GoSigner/ipa/archive"
)

// The planned archive is never written, so nothing downstream can check it:
// iOS reads it once, and a byte out of place is an install that fails with no
// reason given. This signs the same input both ways and holds the plan to the
// written archive — same entries, same sizes — then makes zip's own reader
// verify every entry's CRC out of the generated bytes, and finally checks that
// serving an arbitrary range gives exactly the bytes at that offset (which is
// what a resumed install asks for).
//
//	PLAN_IPA=/path/app.ipa PLAN_P12=/path/cert.p12 PLAN_P12_PASSWORD=x go test ./ipa/pipeline -run TestPlan
func TestPlanDescribesTheSameArchive(t *testing.T) {
	input := os.Getenv("PLAN_IPA")
	p12 := os.Getenv("PLAN_P12")
	if input == "" || p12 == "" {
		t.Skip("set PLAN_IPA and PLAN_P12")
	}

	identity, err := loader.LoadP12(p12, os.Getenv("PLAN_P12_PASSWORD"))
	if err != nil {
		t.Fatalf("load p12: %v", err)
	}

	dir := t.TempDir()
	written := filepath.Join(dir, "written.ipa")
	if err := Resign(&ResignOptions{
		InputPath: input, OutputPath: written, Identity: identity, WorkDir: dir,
	}); err != nil {
		t.Fatalf("write mode: %v", err)
	}

	planned := &ResignOptions{InputPath: input, Identity: identity, WorkDir: dir, Plan: true}
	if err := Resign(planned); err != nil {
		t.Fatalf("plan mode: %v", err)
	}
	if planned.PlanResult == nil {
		t.Fatal("plan mode produced no plan")
	}
	defer os.RemoveAll(planned.PlanResult.WorkDir)

	plan, err := archive.LoadPlan(planned.PlanResult.Path)
	if err != nil {
		t.Fatalf("load plan: %v", err)
	}

	// Materialise it once, the way the install server would stream it.
	virtual := filepath.Join(dir, "virtual.ipa")
	out, err := os.Create(virtual)
	if err != nil {
		t.Fatal(err)
	}
	if err := plan.WriteRange(out, 0, 0); err != nil {
		t.Fatalf("write range: %v", err)
	}
	out.Close()

	info, err := os.Stat(virtual)
	if err != nil {
		t.Fatal(err)
	}
	if info.Size() != plan.Length() {
		t.Fatalf("length %d, wrote %d — iOS is told the wrong size", plan.Length(), info.Size())
	}

	// Every entry readable, every CRC right: zip checks the CRC on read, so a
	// misplaced byte anywhere in the layout fails here.
	got, err := zip.OpenReader(virtual)
	if err != nil {
		t.Fatalf("the generated archive does not open: %v", err)
	}
	defer got.Close()
	for _, f := range got.File {
		rc, err := f.Open()
		if err != nil {
			t.Fatalf("open %s: %v", f.Name, err)
		}
		if _, err := io.Copy(io.Discard, rc); err != nil {
			t.Fatalf("read %s: %v", f.Name, err)
		}
		rc.Close()
	}

	// The same entries as the archive that was written to disk.
	want, err := zip.OpenReader(written)
	if err != nil {
		t.Fatal(err)
	}
	defer want.Close()
	if len(want.File) != len(got.File) {
		t.Fatalf("entries: written %d, planned %d", len(want.File), len(got.File))
	}
	for i, w := range want.File {
		g := got.File[i]
		if w.Name != g.Name {
			t.Fatalf("entry %d: written %q, planned %q", i, w.Name, g.Name)
		}
		if w.UncompressedSize64 != g.UncompressedSize64 {
			t.Fatalf("%s: size written %d, planned %d", w.Name, w.UncompressedSize64, g.UncompressedSize64)
		}
		if w.Method != g.Method {
			t.Fatalf("%s: method written %d, planned %d", w.Name, w.Method, g.Method)
		}
		if w.Mode() != g.Mode() {
			t.Fatalf("%s: mode written %v, planned %v", w.Name, w.Mode(), g.Mode())
		}
	}

	// A resumed install asks for a range; it must be the same bytes.
	full, err := os.Open(virtual)
	if err != nil {
		t.Fatal(err)
	}
	defer full.Close()
	random := rand.New(rand.NewSource(7))
	for i := 0; i < 24; i++ {
		offset := random.Int63n(plan.Length())
		length := random.Int63n(1 << 20)
		if length == 0 || offset+length > plan.Length() {
			length = plan.Length() - offset
		}

		var served bytes.Buffer
		if err := plan.WriteRange(&served, offset, length); err != nil {
			t.Fatalf("range %d+%d: %v", offset, length, err)
		}
		expected := make([]byte, length)
		if _, err := full.ReadAt(expected, offset); err != nil {
			t.Fatal(err)
		}
		if !bytes.Equal(served.Bytes(), expected) {
			t.Fatalf("range %d+%d differs from the archive", offset, length)
		}
	}
}
